import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    backgroundColor: "var(--bg-main)",
    color: "var(--text-primary)",
    padding: "20px",
  },
  header: {
    borderBottom: "1px solid var(--border-color)",
    paddingBottom: "16px",
    marginBottom: "24px",
  },
  title: {
    fontSize: "28px",
    fontWeight: 700,
    marginBottom: "8px",
  },
  subtitle: {
    fontSize: "20px",
    marginBottom: "16px",
    color: "var(--text-secondary)",
  },
  changeMatchBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 16px",
    borderRadius: "8px",
    background: "rgba(255, 255, 255, 0.05)",
    color: "var(--text-secondary)",
    fontSize: "13px",
    fontWeight: 600,
    border: "1px solid var(--border-color)",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    marginTop: "12px",
  },
  resetBtn: {
    backgroundColor: "var(--secondary-color)",
    color: "var(--text-primary)",
    padding: "10px 20px",
    borderRadius: "var(--border-radius)",
    fontSize: "14px",
    fontWeight: 600,
    border: "1px solid var(--border-color)",
    cursor: "pointer",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  content: {
    maxWidth: "1200px",
    margin: "0 auto",
  },
  matchList: {
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
  },
  matchItem: {
    backgroundColor: "var(--bg-card)",
    padding: "20px",
    borderRadius: "var(--border-radius)",
    cursor: "pointer",
    border: "1px solid var(--border-color)",
    transition: "all 0.2s",
  },
  matchInfo: {
    display: "flex",
    gap: "8px",
    marginBottom: "12px",
  },
  sportBadge: {
    backgroundColor: "var(--accent-color)",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
    fontWeight: 600,
  },
  categoryBadge: {
    backgroundColor: "var(--secondary-color)",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "12px",
  },
  matchTeams: {
    fontSize: "16px",
    fontWeight: 600,
    marginBottom: "8px",
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  vs: {
    color: "var(--text-secondary)",
    fontSize: "14px",
  },
  matchDateTime: {
    fontSize: "14px",
    color: "var(--text-secondary)",
  },
  noMatches: {
    color: "var(--text-secondary)",
    textAlign: "center",
    padding: "40px",
  },
  scoreboard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "var(--bg-card)",
    padding: "32px",
    borderRadius: "var(--border-radius)",
    marginBottom: "24px",
    border: "2px solid var(--border-color)",
  },
  team: {
    flex: 1,
    textAlign: "center",
  },
  teamLeft: {
    flex: 1,
    textAlign: "left",
  },
  teamRight: {
    flex: 1,
    textAlign: "right",
  },
  teamName: {
    fontSize: "1.4rem",
    lineHeight: 1.3,
    margin: 0,
  },
  score: {
    fontSize: "64px",
    fontWeight: 700,
    color: "white",
    marginTop: "8px",
  },
  timeDisplay: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "8px",
    padding: "0 40px",
  },
  minute: {
    fontSize: "32px",
    fontWeight: 700,
  },
  liveBadge: {
    backgroundColor: "var(--live-color)",
    color: "white",
    padding: "4px 12px",
    borderRadius: "12px",
    fontSize: "12px",
    fontWeight: 700,
    letterSpacing: "0.4px",
    marginTop: "8px",
    whiteSpace: "nowrap",
    display: "inline-flex",
    alignItems: "center",
  },
  gameControls: {
    backgroundColor: "var(--bg-card)",
    padding: "24px",
    borderRadius: "var(--border-radius)",
    marginBottom: "24px",
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: 600,
    marginBottom: "16px",
  },
  controlButtons: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "12px",
  },
  controlBtn: {
    padding: "12px 20px",
    borderRadius: "var(--border-radius)",
    fontSize: "14px",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.2s",
    border: "1px solid",
  },
  startBtn: {
    backgroundColor: "#22c55e",
    color: "white",
    borderColor: "#16a34a",
  },
  pauseBtn: {
    backgroundColor: "#f59e0b",
    color: "white",
    borderColor: "#d97706",
  },
  resumeBtn: {
    backgroundColor: "#3b82f6",
    color: "white",
    borderColor: "#2563eb",
  },
  endBtn: {
    backgroundColor: "#ef4444",
    color: "white",
    borderColor: "#dc2626",
  },
  eventSection: {
    backgroundColor: "var(--bg-card)",
    padding: "24px",
    borderRadius: "var(--border-radius)",
    marginBottom: "16px",
  },
  eventButtons: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px",
  },
  eventBtn: {
    padding: "16px",
    borderRadius: "var(--border-radius)",
    fontSize: "14px",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.2s",
    border: "1px solid",
  },
  teamABtn: {
    backgroundColor: "#1e40af",
    color: "white",
    borderColor: "#1e3a8a",
  },
  teamBBtn: {
    backgroundColor: "#b91c1c",
    color: "white",
    borderColor: "#991b1b",
  },
  yellowBtn: {
    backgroundColor: "#ca8a04",
    color: "white",
    borderColor: "#a16207",
  },
  redBtn: {
    backgroundColor: "#dc2626",
    color: "white",
    borderColor: "#b91c1c",
  },
  penaltyBtn: {
    backgroundColor: "#7c3aed",
    color: "white",
    borderColor: "#6d28d9",
  },
  penaltyMissedBtn: {
    backgroundColor: "#475569",
    color: "white",
    borderColor: "#334155",
  },
  modal: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "var(--bg-card)",
    padding: "32px",
    borderRadius: "var(--border-radius)",
    width: "min(420px, calc(100vw - 24px))",
    border: "1px solid var(--border-color)",
  },
  modalContentLarge: {
    backgroundColor: "var(--bg-card)",
    padding: "32px",
    borderRadius: "var(--border-radius)",
    width: "min(600px, calc(100vw - 24px))",
    maxWidth: "600px",
    maxHeight: "80vh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border-color)",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: 600,
    marginBottom: "12px",
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: "14px",
    color: "var(--text-secondary)",
    textAlign: "center",
    marginBottom: "20px",
    fontWeight: 600,
  },
  playerList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    overflowY: "auto",
    maxHeight: "400px",
    marginBottom: "16px",
    paddingRight: "8px",
  },
  playerItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    backgroundColor: "var(--bg-main)",
    border: "1px solid var(--border-color)",
    borderRadius: "var(--border-radius)",
    cursor: "pointer",
    transition: "all 0.2s",
    textAlign: "left",
  },
  playerItemDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
    backgroundColor: "var(--secondary-color)",
  },
  playerName: {
    fontSize: "15px",
    fontWeight: 500,
    flex: 1,
  },
  playerStats: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  statBadge: {
    fontSize: "12px",
    padding: "2px 8px",
    borderRadius: "10px",
    backgroundColor: "var(--secondary-color)",
    fontWeight: 600,
  },
  statBadgeRed: {
    fontSize: "12px",
    padding: "2px 8px",
    borderRadius: "10px",
    backgroundColor: "var(--live-color)",
    color: "white",
    fontWeight: 700,
  },
  modalButtons: {
    display: "flex",
    gap: "12px",
  },
  modalBtn: {
    flex: 1,
    padding: "12px",
    borderRadius: "var(--border-radius)",
    fontSize: "14px",
    fontWeight: 600,
  },
  confirmBtn: {
    backgroundColor: "var(--accent-color)",
    color: "white",
  },
  cancelBtn: {
    backgroundColor: "var(--secondary-color)",
    color: "var(--text-primary)",
  },
  timeline: {
    backgroundColor: "var(--bg-card)",
    padding: "24px",
    borderRadius: "var(--border-radius)",
    marginTop: "24px",
  },
  timelineList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  timelineItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    padding: "8px 10px",
    backgroundColor: "var(--bg-main)",
    borderRadius: "var(--border-radius)",
    border: "1px solid var(--border-color)",
    justifyContent: "flex-start",
  },
  eventTimePill: {
    fontWeight: 700,
    color: "white",
    minWidth: "40px",
    textAlign: "center",
    fontSize: "12px",
    background: "var(--accent-color)",
    borderRadius: "999px",
    padding: "4px 8px",
    flexShrink: 0,
  },
  eventIconBubble: {
    fontSize: "18px",
    width: "32px",
    height: "32px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "999px",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid var(--border-color)",
    flexShrink: 0,
  },
  eventContentWrap: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: "6px",
  },
  eventText: {
    flex: 1,
    minWidth: 0,
    fontSize: "14px",
    lineHeight: 1.4,
    wordBreak: "break-word",
  },
  eventMetaTag: {
    fontSize: "11px",
    color: "var(--text-secondary)",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid var(--border-color)",
    borderRadius: "999px",
    padding: "4px 8px",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  noEvents: {
    color: "var(--text-secondary)",
    textAlign: "center",
    padding: "20px",
  },
};